import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faArrowUp,
  faBell,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faCircle,
  faChevronDown,
  faCircleNotch,
  faClipboard,
  faClock,
  faCog,
  faEllipsisV,
  faExclamationTriangle,
  faExternalLinkAlt,
  faFlag,
  faInfoCircle,
  faMapMarkerAlt,
  faPlus,
  faPrint,
  faSearch,
  faTimes,
  faTimesCircle,
  faUpload,
  faUser,
  faCommentAlt as fasFaCommentAlt,
  faTrashAlt,
  faTasks,
  faList,
  faChartBar,
  faAngleLeft,
  faAngleDoubleLeft,
  faAngleRight,
  faAngleDoubleRight,
} from '@fortawesome/free-solid-svg-icons'
import {
  faCommentAlt as farFaCommentAlt,
  faSquare as farFaSquare,
  faCircle as farFaCircle,
} from '@fortawesome/free-regular-svg-icons'

library.add(
  faArrowUp,
  faBell,
  faCheck,
  faCheckCircle,
  faCheckSquare,
  faCircle,
  farFaSquare,
  faChevronDown,
  faCircleNotch,
  faClipboard,
  faClock,
  faCog,
  faEllipsisV,
  faExclamationTriangle,
  faExternalLinkAlt,
  faFlag,
  faInfoCircle,
  faMapMarkerAlt,
  faPlus,
  faPrint,
  faSearch,
  faTimes,
  faTimesCircle,
  faUpload,
  faUser,
  fasFaCommentAlt,
  farFaCommentAlt,
  faTrashAlt,
  faTasks,
  faList,
  faChartBar,
  faAngleLeft,
  faAngleDoubleLeft,
  faAngleRight,
  faAngleDoubleRight,
  farFaCircle
)

export const ICON_NAMES = [
  ...Object.keys(library.definitions.fas).map(name => ['fas', name]),
  [farFaCommentAlt.prefix, farFaCommentAlt.iconName],
  [farFaSquare.prefix, farFaSquare.iconName],
  [farFaCircle.prefix, farFaCircle.iconName],
]
